### ISSUE TITLE
membersOnline value is wrong

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/testausapis#6]
I doubt there is 1 300 members online when Discord shows there are just 300 members in the Jäsen-role.

Needs investigating.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/46541386/167154529-3ca5f4ef-45d7-4048-985d-1dff1440085a.png">

<img width="130" alt="image" src="https://user-images.githubusercontent.com/46541386/167154587-a5f0b574-1206-4337-b69f-caa2bcf818a6.png">

**Comment by Chicken** [comment]
This happens because the check for a member being online (`member?.presence?.status !== "offline"`) is wrong. When a presence is not in the cache the status (`member?.presence?.status`) is `undefined` and therefore the code thinks such members are online when in reality they are more likely to be offline. For a good approximate amount of online users `guild.approximatePresenceCount` should be used.

**Comment by Esinko** [comment]
Unsure about how you should calculate how many members are online, but this is just a plain bug in my code. I should have added an exception for fields with `undefined`. However, I wonder how this seemed to work before...

**Comment by ahnl** [comment]
Thank you:)
